import { Link } from "@tanstack/react-router";
import { useEffect, useState, type FormEvent } from "react";
import { ArrowRight, CalendarDays, Check, ChevronLeft, ChevronRight, Facebook, Instagram, Mail, MapPin, Menu, MessageCircle, Phone, ShieldCheck, Sparkles, Stethoscope, X, Youtube } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { clinic, featuredSlugs, services, type Service } from "@/lib/clinic-data";

export function Logo() {
  return <Link to="/" className="group flex items-center gap-3" aria-label="ROOTS Dental Clinic home"><span className="grid size-11 place-items-center rounded-full bg-primary text-primary-foreground shadow-sm transition-transform group-hover:rotate-3"><span className="text-xl font-bold">R</span></span><span><strong className="block font-display text-[17px] leading-none text-foreground">ROOTS</strong><span className="mt-1 block text-[9px] font-bold uppercase tracking-[0.22em] text-muted-foreground">Dental Clinic</span></span></Link>;
}

const nav = [{ label: "Home", to: "/" as const }, { label: "About Us", to: "/about" as const }, { label: "Our Doctors", to: "/doctors" as const }, { label: "Our Services", to: "/services" as const }, { label: "Contact Us", to: "/contact" as const }];

export function Header() {
  const [open, setOpen] = useState(false);
  return <header className="sticky top-0 z-40 border-b border-border/70 bg-background/95 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8"><Logo /><nav className="hidden items-center gap-1 lg:flex" aria-label="Main navigation">{nav.map((item) => <Link key={item.to} to={item.to} className="rounded-md px-4 py-2 text-sm font-semibold text-muted-foreground transition-colors hover:bg-accent hover:text-foreground" activeProps={{ className: "text-primary bg-accent" }} activeOptions={{ exact: item.to === "/" }}>{item.label}</Link>)}</nav><div className="hidden lg:block"><Button asChild size="lg"><Link to="/contact"><CalendarDays /> Book an Appointment</Link></Button></div><Button variant="ghost" size="icon" className="lg:hidden" onClick={() => setOpen(!open)} aria-label="Open navigation" aria-expanded={open}>{open ? <X /> : <Menu />}</Button></div>{open && <nav className="border-t bg-background px-5 py-4 lg:hidden" aria-label="Mobile navigation"><div className="mx-auto grid max-w-7xl gap-1">{nav.map((item) => <Link key={item.to} to={item.to} onClick={() => setOpen(false)} className="rounded-md px-3 py-3 font-semibold text-foreground hover:bg-accent">{item.label}</Link>)}<Button asChild size="lg" className="mt-2"><Link to="/contact" onClick={() => setOpen(false)}>Book an Appointment</Link></Button></div></nav>}</header>;
}

export function Footer() {
  return <footer className="bg-footer text-footer-foreground pb-24 lg:pb-0"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-16 sm:grid-cols-2 lg:grid-cols-[1.25fr_.7fr_1fr_1.25fr] lg:px-8"><div><Logo /><p className="mt-5 max-w-sm text-sm leading-7 text-footer-muted">Comprehensive dental care focused on healthy smiles, advanced treatment and compassionate patient care.</p><div className="mt-6 flex gap-2">{[[Instagram,"Instagram","#"],[Facebook,"Facebook","#"],[Youtube,"YouTube","#"],[MessageCircle,"WhatsApp",clinic.whatsapp]].map(([Icon,label,href]) => <a key={String(label)} href={String(href)} aria-label={String(label)} className="grid size-10 place-items-center rounded-full border border-footer-border text-footer-muted transition-colors hover:bg-primary hover:text-primary-foreground"><Icon className="size-4" /></a>)}</div></div><FooterCol title="Quick Links" items={nav.map(n => [n.label,n.to])} /><FooterCol title="Our Services" items={services.slice(0,8).map(s => [s.title,`/services/${s.slug}`])} /><div><h2 className="font-display text-lg">Contact Us</h2><div className="mt-5 grid gap-4 text-sm text-footer-muted"><a className="flex gap-3 hover:text-footer-foreground" href={`tel:${clinic.phone}`}><Phone className="mt-0.5 size-4 shrink-0" />{clinic.phone}</a><a className="flex gap-3 hover:text-footer-foreground" href={`mailto:${clinic.email}`}><Mail className="mt-0.5 size-4 shrink-0" />{clinic.email}</a><address className="flex gap-3 not-italic leading-6"><MapPin className="mt-0.5 size-4 shrink-0" />{clinic.address}</address></div></div></div><div className="border-t border-footer-border"><div className="mx-auto max-w-7xl px-5 py-5 text-xs text-footer-muted lg:px-8">© 2026 ROOTS DENTAL CLINIC. All Rights Reserved.</div></div></footer>;
}
function FooterCol({ title, items }: { title: string; items: string[][] }) { return <div><h2 className="font-display text-lg">{title}</h2><ul className="mt-5 grid gap-3 text-sm text-footer-muted">{items.map(([label,to]) => <li key={label}><Link to={to as "/"} className="transition-colors hover:text-footer-foreground">{label}</Link></li>)}</ul></div>; }

export function MobileActions() { return <div className="fixed inset-x-0 bottom-0 z-40 grid grid-cols-3 border-t bg-background p-2 shadow-2xl lg:hidden"><Button asChild variant="ghost"><a href={`tel:${clinic.phone}`}><Phone /> Call</a></Button><Button asChild variant="ghost"><a href={clinic.whatsapp} target="_blank" rel="noreferrer"><MessageCircle /> WhatsApp</a></Button><Button asChild><Link to="/contact"><CalendarDays /> Book</Link></Button></div>; }

export function PageHero({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <section className="page-hero"><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8 lg:py-24"><p className="eyebrow">{eyebrow}</p><h1 className="mt-4 max-w-4xl font-display text-4xl leading-tight text-foreground sm:text-5xl lg:text-6xl">{title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">{text}</p></div></section>; }

export function SectionHeading({ eyebrow, title, text, centered=false }: { eyebrow: string; title: string; text?: string; centered?: boolean }) { return <div className={centered ? "mx-auto max-w-3xl text-center" : "max-w-3xl"}><p className="eyebrow">{eyebrow}</p><h2 className="mt-3 font-display text-3xl leading-tight text-foreground sm:text-4xl">{title}</h2>{text && <p className="mt-4 text-base leading-7 text-muted-foreground sm:text-lg">{text}</p>}</div>; }

export function ServiceCard({ service }: { service: Service }) { return <article className="service-card group"><div className="aspect-[4/3] overflow-hidden"><img src={service.image} alt={service.alt} width={480} height={360} loading="lazy" className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-[1.04]" /></div><div className="p-6"><h3 className="font-display text-xl text-foreground">{service.title}</h3><p className="mt-2 min-h-14 text-sm leading-6 text-muted-foreground">{service.short}</p><Button asChild variant="link" className="mt-3 h-auto p-0"><Link to="/services/$slug" params={{ slug: service.slug }}>Learn More <ArrowRight /></Link></Button></div></article>; }

export function ServicesSlider() {
  const featured = featuredSlugs.map(slug => services.find(s => s.slug === slug)).filter((s): s is Service => Boolean(s));
  const [active, setActive] = useState(0);
  useEffect(() => { const timer = window.setInterval(() => setActive(i => (i + 1) % featured.length), 4500); return () => window.clearInterval(timer); }, [featured.length]);
  const move = (direction: number) => setActive(i => (i + direction + featured.length) % featured.length);
  return <div className="relative overflow-hidden rounded-lg bg-card shadow-premium"><div className="grid lg:grid-cols-[1.15fr_.85fr]"><div className="relative aspect-[4/3] overflow-hidden lg:aspect-auto lg:min-h-[440px]"><img key={featured[active].slug} src={featured[active].image} alt={featured[active].alt} className="h-full w-full animate-soft-in object-cover" width={800} height={600} /></div><div className="flex flex-col justify-center p-7 sm:p-10 lg:p-12"><span className="text-xs font-bold uppercase tracking-[0.18em] text-primary">Featured treatment {active + 1} / {featured.length}</span><h3 className="mt-4 font-display text-3xl text-foreground">{featured[active].title}</h3><p className="mt-4 leading-7 text-muted-foreground">{featured[active].intro}</p><Button asChild className="mt-7 w-fit"><Link to="/services/$slug" params={{ slug: featured[active].slug }}>Learn More <ArrowRight /></Link></Button><div className="mt-9 flex items-center justify-between"><div className="flex gap-2">{featured.map((s,i) => <button key={s.slug} onClick={() => setActive(i)} aria-label={`Show ${s.title}`} className={`h-2 rounded-full transition-all ${i === active ? "w-8 bg-primary" : "w-2 bg-border"}`} />)}</div><div className="flex gap-2"><Button variant="outline" size="icon" onClick={() => move(-1)} aria-label="Previous service"><ChevronLeft /></Button><Button variant="outline" size="icon" onClick={() => move(1)} aria-label="Next service"><ChevronRight /></Button></div></div></div></div></div>;
}

export function CtaBanner() { return <section className="bg-primary text-primary-foreground"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 px-5 py-14 lg:flex-row lg:items-center lg:px-8"><div><h2 className="font-display text-3xl sm:text-4xl">Ready to Take the Next Step Towards a Healthier Smile?</h2><p className="mt-3 text-primary-foreground/80">Schedule your consultation with our dental care team today.</p></div><div className="flex flex-wrap gap-3"><Button asChild variant="secondary" size="lg"><Link to="/contact"><CalendarDays /> Book an Appointment</Link></Button><Button asChild variant="outlineLight" size="lg"><a href={`tel:${clinic.phone}`}><Phone /> {clinic.phone}</a></Button></div></div></section>; }

export function AppointmentForm() {
  const [sent,setSent]=useState(false); const [error,setError]=useState("");
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault(); const data=new FormData(e.currentTarget); if(!data.get("name")||!data.get("mobile")||!data.get("date")||!data.get("service")){setError("Please complete the required fields.");return;} setError("");setSent(true);e.currentTarget.reset();}
  if(sent) return <div className="rounded-lg border border-success/30 bg-success-soft p-8 text-center"><span className="mx-auto grid size-12 place-items-center rounded-full bg-success text-success-foreground"><Check /></span><h2 className="mt-4 font-display text-2xl">Request received</h2><p className="mt-2 text-muted-foreground">Thank you. The clinic team will contact you to discuss availability and confirm your appointment.</p><Button className="mt-5" variant="outline" onClick={()=>setSent(false)}>Send another request</Button></div>;
  return <form onSubmit={submit} className="grid gap-5" noValidate><div className="grid gap-5 sm:grid-cols-2"><Field label="Name *"><input name="name" className="field" placeholder="Your full name" /></Field><Field label="Mobile Number *"><input name="mobile" inputMode="tel" className="field" placeholder="10-digit number" /></Field><Field label="Email"><input name="email" type="email" className="field" placeholder="you@example.com" /></Field><Field label="Preferred Date *"><input name="date" type="date" className="field" /></Field><Field label="Preferred Time"><input name="time" type="time" className="field" /></Field><Field label="Service / Treatment *"><select name="service" className="field"><option value="">Select a service</option>{services.map(s=><option key={s.slug} value={s.title}>{s.title}</option>)}</select></Field></div><Field label="Message"><textarea name="message" rows={4} className="field resize-none" placeholder="Tell us briefly how we can help" /></Field>{error && <p className="text-sm font-medium text-destructive" role="alert">{error}</p>}<Button type="submit" size="lg" className="w-fit">Request an Appointment <ArrowRight /></Button><p className="text-xs leading-5 text-muted-foreground">Submitting this form does not automatically confirm an appointment. ROOTS DENTAL CLINIC will contact you to discuss and confirm availability.</p></form>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="grid gap-2 text-sm font-semibold text-foreground"><span>{label}</span>{children}</label>}

export function ServiceFaq({ service }: { service: Service }) { const faqs=[{q:`Is ${service.title.toLowerCase()} right for me?`,a:"Suitability depends on your oral health, symptoms and individual needs. A clinical examination allows the dentist to discuss appropriate options with you."},{q:"What should I expect at the first visit?",a:"Your visit usually begins with a discussion of your concern and health history, followed by an examination and any clinically appropriate diagnostic records."},{q:"How should I prepare?",a:"Bring relevant medical information and previous dental records if available. Continue your normal oral hygiene routine unless the clinic advises otherwise."}]; return <Accordion type="single" collapsible className="rounded-lg border bg-card px-6">{faqs.map((faq,i)=><AccordionItem key={faq.q} value={`faq-${i}`}><AccordionTrigger className="py-5 text-base">{faq.q}</AccordionTrigger><AccordionContent className="leading-7 text-muted-foreground">{faq.a}</AccordionContent></AccordionItem>)}</Accordion>; }

export const trustItems=[{icon:Stethoscope,title:"Experienced Dental Professionals",text:"Dedicated dental professionals focused on personalized treatment."},{icon:Sparkles,title:"Comprehensive Dental Care",text:"Thoughtful dental care for children, adults and seniors under one roof."},{icon:ShieldCheck,title:"Advanced Technology",text:"Modern equipment supports careful diagnosis, precision and comfort."},{icon:MessageCircle,title:"Patient-Centric Approach",text:"Treatment plans shaped around each patient's individual needs."},{icon:Check,title:"Hygiene & Safety",text:"High standards of sterilization, infection control and clinical hygiene."},{icon:CalendarDays,title:"Comfortable Environment",text:"A welcoming setting designed to make dental visits feel easier."}];
